### ISSUE TITLE
Launch landing page

### ISSUE THREAD

**Issue by trulister-dev** [trulister/trulister.github.io#4]
### Strategic Goals
- [x] Launch trulister.com

#### Backend
- [x] Remove package.json / package.lock
- [x] Remove `rel` link for Jotform
- [x] Add CNAME to project repository
- [x] [Point Name Cheap CNAME to repository ](https://www.namecheap.com/support/knowledgebase/article.aspx/9645/2208/how-do-i-link-my-domain-to-github-pages/)
- [ ] Google SEO Account

#### Frontend
- [ ] Determine & update theme colors
- [ ] Determine & update fonts
- [ ] Acquire correctly sized logos & favicons

**Comment by trulister-pm** [comment]
closed
